
# Use the official PHP image
FROM php:8.2-cli

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the PHP script into the container
COPY index.php .

# Command to run the PHP script
CMD [ "f1", "./f1.php" ]

